"use client";
import Link from "next/link";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowRight,Sparkles} from "lucide-react";
import {call} from "../lib/api";
export default function Login(){
  const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const router=useRouter();
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const x=await call("/auth/login",{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("access_token",x.access_token);localStorage.setItem("refresh_token",x.refresh_token);router.push("/dashboard")}catch(e){setError(e instanceof Error?e.message:"Erro inesperado")}finally{setBusy(false)}}
  return <main className="grid min-h-screen bg-white md:grid-cols-2"><section className="grid-bg hidden border-r border-zinc-200 p-12 md:flex md:flex-col md:justify-between"><Link href="/" className="flex items-center gap-2 text-xl font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-zinc-950 text-white"><Sparkles size={18}/></span>SolvitSoft IA</Link><div><h2 className="max-w-lg text-4xl font-semibold leading-tight tracking-tight">Uma única conversa para todas as tarefas da sua equipe.</h2><p className="mt-5 max-w-md leading-7 text-zinc-500">Texto, documentos, imagens e especialistas empresariais em um ambiente simples e protegido.</p></div><p className="text-sm text-zinc-500">Dados isolados por empresa</p></section><section className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-sm"><div className="mb-10 flex items-center gap-2 md:hidden"><span className="grid h-9 w-9 place-items-center rounded-xl bg-zinc-950 text-white"><Sparkles size={18}/></span><span className="font-semibold">SolvitSoft IA</span></div><p className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Bem-vindo de volta</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Entre no workspace</h1><p className="mt-3 text-zinc-500">Use seu e-mail corporativo para continuar.</p>{error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<label className="mt-8 block text-sm font-medium">E-mail<input className="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 outline-none focus:border-zinc-600" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="mt-5 block text-sm font-medium">Senha<input className="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 outline-none focus:border-zinc-600" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-zinc-950 py-3 font-medium text-white disabled:opacity-50">{busy?"Entrando...":"Entrar"}<ArrowRight size={17}/></button><p className="mt-6 text-center text-sm text-zinc-500">Ainda não tem uma empresa? <Link className="font-medium text-zinc-950" href="/cadastro">Criar conta</Link></p></form></section></main>
}
