"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ArrowUp,Sparkles} from "lucide-react";
import {API} from "../lib/api";
type Message={role:"user"|"assistant";content:string;image?:string};
export default function FreeChat(){
  const [device,setDevice]=useState("");const [text,setText]=useState("");const [messages,setMessages]=useState<Message[]>([]);const [busy,setBusy]=useState(false);const [credits,setCredits]=useState(100);const [blocked,setBlocked]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{let id=localStorage.getItem("solvitsoft_device_id");if(!id){id=crypto.randomUUID()+"-"+crypto.randomUUID();localStorage.setItem("solvitsoft_device_id",id)}setDevice(id)},[]);
  async function send(e:React.FormEvent){e.preventDefault();if(!text.trim()||busy)return;const prompt=text;setText("");setMessages(v=>[...v,{role:"user",content:prompt}]);setBusy(true);setError("");try{const response=await fetch(API+"/anonymous/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({device_id:device,message:prompt})});const data=await response.json();if(response.status===402){setBlocked(true);throw new Error(data.detail?.message||"Limite gratuito atingido")}if(!response.ok)throw new Error(data.detail||"Erro inesperado");setCredits(data.credit_balance);setMessages(v=>[...v,{role:"assistant",content:data.message,image:data.image}])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <main className="flex min-h-screen flex-col bg-white"><header className="flex h-16 items-center justify-between border-b px-5"><div className="flex items-center gap-2 font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-zinc-950 text-white"><Sparkles size={17}/></span>SolvitSoft IA</div><div className="flex gap-2"><Link href="/login" className="rounded-xl border px-4 py-2 text-sm">Entrar</Link><Link href="/cadastro" className="rounded-xl bg-zinc-950 px-4 py-2 text-sm text-white">Criar conta</Link></div></header><section className="mx-auto flex w-full max-w-3xl flex-1 flex-col px-5 py-8">{!messages.length?<div className="m-auto w-full text-center"><h1 className="text-3xl font-semibold">Como posso ajudar?</h1><p className="mt-2 text-sm text-zinc-500">Use gratuitamente sem cadastro. Sua franquia fica salva neste navegador.</p></div>:<div className="space-y-6">{messages.map((m,i)=><div key={i} className={m.role==="user"?"ml-auto max-w-[80%] rounded-3xl bg-zinc-100 px-5 py-3":"max-w-full"}>{m.image&&<img src={m.image} className="mb-3 max-h-[500px] rounded-2xl" alt="Imagem gerada"/>}<div className="whitespace-pre-wrap text-sm leading-7">{m.content}</div></div>)}{busy&&<p className="animate-pulse text-sm text-zinc-500">Pensando...</p>}</div>}</section><div className="sticky bottom-0 bg-white px-4 pb-5"><form onSubmit={send} className="mx-auto flex max-w-3xl items-end gap-2 rounded-2xl border bg-white p-3 shadow-xl"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Envie uma mensagem..." className="min-h-11 flex-1 resize-none bg-transparent p-2 outline-none"/><button disabled={busy||!text.trim()||blocked} className="grid h-10 w-10 place-items-center rounded-full bg-zinc-950 text-white disabled:bg-zinc-300"><ArrowUp size={18}/></button></form><div className="mx-auto mt-2 flex max-w-3xl justify-between text-xs text-zinc-500"><span>{credits} de 100 créditos restantes</span><span>Plano gratuito neste navegador</span></div>{error&&<div className="mx-auto mt-3 max-w-3xl rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}{blocked&&<span> — <Link href="/cadastro" className="font-semibold underline">Criar conta</Link></span>}</div>}</div></main>
}
