"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {Sparkles} from "lucide-react";
import {call} from "../lib/api";
export default function Cadastro(){
  const [form,setForm]=useState({company_name:"",document:"",name:"",email:"",password:""});const [error,setError]=useState("");const router=useRouter();
  async function submit(e:React.FormEvent){e.preventDefault();try{const x=await call("/auth/register",{method:"POST",body:JSON.stringify(form)});localStorage.setItem("access_token",x.access_token);localStorage.setItem("refresh_token",x.refresh_token);router.push("/dashboard")}catch(e){setError(e instanceof Error?e.message:"Erro inesperado")}}
  const fields:Array<[keyof typeof form,string,string]>=[["company_name","Nome da empresa","text"],["document","CNPJ (opcional)","text"],["name","Seu nome","text"],["email","E-mail corporativo","email"],["password","Senha com pelo menos 8 caracteres","password"]];
  return <main className="grid-bg flex min-h-screen items-center justify-center bg-white p-6"><form onSubmit={submit} className="w-full max-w-xl rounded-3xl border border-zinc-200 bg-white p-8 shadow-2xl shadow-zinc-200/60 md:p-10"><Link href="/" className="flex items-center gap-2 text-sm font-semibold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-zinc-950 text-white"><Sparkles size={15}/></span>SolvitSoft IA</Link><h1 className="mt-8 text-4xl font-semibold tracking-tight">Crie seu workspace</h1><p className="mt-2 text-zinc-500">Configure sua empresa e comece a trabalhar com IA.</p>{error&&<p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-7 grid gap-4 md:grid-cols-2">{fields.map(([key,label,type],i)=><label className={i===4?"md:col-span-2":""} key={key}><span className="text-sm font-medium">{label}</span><input type={type} required={key!=="document"} minLength={key==="password"?8:undefined} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 outline-none focus:border-zinc-600"/></label>)}</div><button className="mt-7 w-full rounded-xl bg-zinc-950 py-3 font-medium text-white">Criar workspace</button><p className="mt-5 text-center text-sm text-zinc-500">Já possui conta? <Link href="/login" className="font-medium text-zinc-950">Entrar</Link></p></form></main>
}
