"use client";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {useState} from "react";
import {call} from "../lib/api";
export default function ResetPassword(){
  const params=useSearchParams(); const token=params.get("token")||""; const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setError("");if(password!==confirm){setError("As senhas não são iguais.");return}setBusy(true);try{const data=await call("/auth/password/reset",{method:"POST",body:JSON.stringify({token,password})});setMessage(data.message)}catch(e){setError(e instanceof Error?e.message:"Não foi possível redefinir a senha")}finally{setBusy(false)}}
  return <main className="flex min-h-screen items-center justify-center bg-white p-6"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-zinc-200 p-8 shadow-xl"><h1 className="text-3xl font-semibold">Crie uma nova senha</h1><p className="mt-3 text-zinc-500">Ao concluir, todas as sessões anteriores serão encerradas.</p>{message&&<p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}{error&&<p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!message&&<><label className="mt-6 block text-sm font-medium">Nova senha<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3"/></label><label className="mt-4 block text-sm font-medium">Confirme a senha<input type="password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-300 px-4 py-3"/></label><button disabled={busy||!token} className="mt-6 w-full rounded-xl bg-zinc-950 py-3 font-medium text-white disabled:opacity-50">{busy?"Salvando...":"Redefinir senha"}</button></>}<Link href="/login" className="mt-5 block text-center text-sm font-medium text-zinc-600">Ir para o login</Link></form></main>
}
